# Change baseurl before deploy
baseurl = "https://403f.cafe/"
locale = "zh"
pagination.pagerSize = 5
title = "403F's Cafe"

# Theme i18n support
# See config/_default/languages.toml for enabled languages.
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

# Set hasCJKLanguage to true if the default language is CJK.
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "sonetto"

googleAnalytics = "G-3PB5N8JWJS"

#[imaging]
#resampleFilter = "lanczos"
#quality = 100