# Change baseurl before deploy
baseurl = "https://403f.cafe/"
languageCode = "zh-cn"
paginate = 5
title = "403F's Cafe"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "sonetto"

googleAnalytics = "G-3PB5N8JWJS"

#[imaging]
#resampleFilter = "lanczos"
#quality = 100