# Uncomment this file to enable multilanguage site support

#[en]
#languageName = "English"
#languagedirection = "ltr"
#title = "403F's Cafe"
#weight = 1

[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "403F的小窝"
weight = 1